### ISSUE TITLE
incorrect light locations format from GPE2

### ISSUE THREAD

**Issue by camrinbraun** [camrinbraun/HMMoce#18]
Issue filed via email by Federico Mas:

* It is my understanding `read.wc` function automatically reads and properly format default generated WC .csv files. However, on the vignette (https://mran.microsoft.com/snapshot/2017-12-11/web/packages/HMMoce/vignettes/Using_HMMoce.html) you also mention a second way to retrieve light data from the tags (Light Based Positions from GPE2 (instead of raw light data from the LigthLocs.csv file)). My issue here is that I am not sure how you produced this .csv file that then you load with the `read.table` function. I have taken a close look to the file provided as an example in the vignette (the blue shark data) and it seems to have the exact same format as the Locations.csv file from WC, but is completely different from the default format of the .csv file generated after porcessing the LightLoc.csv with GPE2. I just can not seem to be able to generate a file with the data type and format that you use in the vignette example. Am I missing something here? As far as I understand, using this method instead of the raw light data is better for latter on likeliehood calculations, parameter estimations and MPT generation. Any idea what I might be doing wrong or what I might be missing?

**Comment by camrinbraun** [comment]
Federico - Its hard for me to diagnose your light location file problem without seeing what it looks like and how you generated your file. Can you send an example of your LightLoc and Locations outputs as well as some explanation of how you got to those outputs? I assume you’ve already used GPE2 on -LightLoc to generate light-based location estimates?

The package ships with example tag data of each type that you can use as a guide.

```
gpe2 <- system.file("extdata", "141259-Locations-GPE2.csv", package = "HMMoce")
locs <- read.table(gpe2, sep = ',', header = T, blank.lines.skip = F)
str(locs)
'data.frame':	606 obs. of  17 variables:
 $ DeployID                 : int  141259 141259 141259 141259 141259 141259 141259 141259 141259 141259 ...
 $ Ptt                      : int  141259 141259 141259 141259 141259 141259 141259 141259 141259 141259 ...
 $ Instr                    : Factor w/ 1 level "MiniPAT": 1 1 1 1 1 1 1 1 1 1 ...
 $ Date                     : Factor w/ 602 levels "2015-10-14 10:28:45",..: 1 2 3 4 5 6 7 8 9 10 ...
 $ Type                     : Factor w/ 2 levels "Argos","GPE": 2 2 2 2 2 2 2 2 2 2 ...
 $ Quality                  : Factor w/ 7 levels "","0","1","2",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ Latitude                 : num  42.5 45 49 45 41.5 45.5 40 39.5 41 35 ...
 $ Longitude                : num  -68.2 -68.8 -68.1 -68.9 -68.7 ...
 $ Error.radius             : logi  NA NA NA NA NA NA ...
 $ Error.Semi.major.axis    : int  1583460 1527900 1416780 1277880 972300 1111200 1027860 1138980 722280 1000080 ...
 $ Error.Semi.minor.axis    : int  71078 58991 16835 46343 27293 38261 20218 224845 54624 18205 ...
 $ Error.Ellipse.orientation: int  0 0 0 0 0 0 0 0 0 0 ...
 $ Offset                   : int  611160 611160 500040 333360 277800 222240 277800 500040 NA 333360 ...
 $ Offset.orientation       : int  0 0 0 0 0 0 0 0 NA 0 ...
 $ GPE.MSD                  : num  6.58 7.19 7.66 5.94 4.18 ...
 $ GPE.U                    : num  187.4 197.7 195.3 136.6 73.1 ...
 $ Comment                  : logi  NA NA NA NA NA NA ...

```

The lat/lon and error estimates where `locs$Type == 'GPE'` is what is used to generate the light-based likelihoods in `calc.gpe2`

**Comment by fmasbervejillo** [comment]
Hi Camrin,

I get the LightLoc and Locations .csv files (as well as all the others) directly from WC portal, or via WC DAP Processor.

Location.csv file structure looks like this: 
```
wd<-paste(getwd())
locs <- read.table("163273-Locations.csv", sep = ',', header = T, blank.lines.skip = F)
str(locs)
'data.frame':	591 obs. of  18 variables:
 $ DeployID                 : int  163273 163273 163273 163273 163273 163273 163273 163273 163273 163273 ...
 $ Ptt                      : int  163273 163273 163273 163273 163273 163273 163273 163273 163273 163273 ...
 $ Instr                    : Factor w/ 1 level "MiniPAT": 1 1 1 1 1 1 1 1 1 1 ...
 $ Date                     : Factor w/ 589 levels "00:00:12 28-Jul-2017",..: 395 427 445 453 497 515 524 551 584 587 ...
 $ Type                     : Factor w/ 1 level "Argos": 1 1 1 1 1 1 1 1 1 1 ...
 $ Quality                  : Factor w/ 6 levels "0","1","2","3",..: 3 4 3 3 4 3 3 3 5 6 ...
 $ Latitude                 : num  -33.2 -33.2 -33.2 -33.2 -33.2 ...
 $ Longitude                : num  -50 -50 -50 -50 -50 ...
 $ Error.radius             : int  360 221 267 260 205 271 258 331 1482 2170 ...
 $ Error.Semi.major.axis    : int  545 429 434 478 268 321 1031 844 3662 4503 ...
 $ Error.Semi.minor.axis    : int  237 113 163 141 157 227 64 129 599 1045 ...
 $ Error.Ellipse.orientation: int  95 71 120 44 42 30 76 93 2 41 ...
 $ Offset                   : logi  NA NA NA NA NA NA ...
 $ Offset.orientation       : logi  NA NA NA NA NA NA ...
 $ GPE.MSD                  : logi  NA NA NA NA NA NA ...
 $ GPE.U                    : logi  NA NA NA NA NA NA ...
 $ Count                    : logi  NA NA NA NA NA NA ...
 $ Comment                  : logi  NA NA NA NA NA NA ...

```
However, there are no `locs$Type == 'GPE'` in this file. According to WC MiniPAT User Guide `locs$GPE.MSD` and `locs$GPE.U` are "Historical. No longer applicable." and they appear blank in my .csv files.

LightLoc.csv (not yet processed with GPE2) file structure looks like this: 
```
lightlocs <- read.table("163273-LightLoc.csv", sep = ',', header = T, blank.lines.skip = F)
> str(lightlocs)
'data.frame':	102 obs. of  51 variables:
 $ Index        : int  NA NA 0 1 2 3 4 5 6 7 ...
 $ DeployID     : int  163273 163273 163273 163273 163273 163273 163273 163273 163273 163273 ...
 $ Ptt          : int  163273 163273 163273 163273 163273 163273 163273 163273 163273 163273 ...
 $ DepthSensor  : logi  NA NA NA NA NA NA ...
 $ Source       : Factor w/ 1 level "Transmission": 1 1 1 1 1 1 1 1 1 1 ...
 $ Instr        : Factor w/ 1 level "MiniPAT": 1 1 1 1 1 1 1 1 1 1 ...
 $ Day          : Factor w/ 51 levels "01-Jul-2017",..: 6 39 8 8 10 10 12 12 14 14 ...
 $ Time         : Factor w/ 69 levels "08:00:00","09:07:30",..: 1 36 33 56 30 44 31 47 29 59 ...
 $ Time.Offset  : int  4 4 4 4 4 4 4 4 4 4 ...
 $ Count        : int  NA NA 9 9 11 11 8 8 10 10 ...
 $ InitLocQ     : Factor w/ 2 levels "","Argos-3": 1 2 1 1 1 1 1 1 1 1 ...
 $ InitTime     : Factor w/ 7 levels "","01:41:04 25-Jul-2017",..: 1 6 1 1 1 1 1 1 1 1 ...
 $ InitLat      : num  NA -33.4 NA NA NA ...
 $ InitLon      : num  NA -49.9 NA NA NA ...
 $ Deepest      : int  NA NA 224 368 368 344 344 272 272 312 ...
 $ SSTTime      : Factor w/ 50 levels "","02:00:00 18-Jul-2017",..: 1 1 8 8 35 35 24 24 18 18 ...
 $ SSTDepth     : int  NA NA 9 9 6 6 6 6 17 17 ...
 $ SSTTemp      : num  NA NA 22.1 22.1 22.4 22.4 21.8 21.8 19.6 19.6 ...
 $ Type         : Factor w/ 4 levels "Begin","Dawn",..: 1 4 2 3 2 3 2 3 2 3 ...
 $ Delta        : int  NA NA 300 300 300 450 600 450 300 300 ...
 $ MinDepth     : int  NA NA 48 48 80 144 112 80 80 112 ...
 $ MaxDepth     : int  NA NA 80 208 240 336 272 208 240 272 ...
 $ AttenShallow : logi  NA NA NA NA NA NA ...
 $ AttenDeep    : logi  NA NA NA NA NA NA ...
 $ TravelMetric : int  NA NA 0 0 0 0 0 0 0 0 ...
 $ FoundPrevious: logi  NA NA NA NA NA NA ...
 $ K            : int  NA NA 19228 11361 42180 17090 18333 36329 10039 46974 ...
 $ LL0          : int  NA NA 119 156 97 145 67 124 65 119 ...
 $ Depth0       : logi  NA NA NA NA NA NA ...
 $ LL1          : int  NA NA 125 149 106 138 79 116 70 116 ...
 $ Depth1       : logi  NA NA NA NA NA NA ...
 $ LL2          : int  NA NA 133 142 113 134 96 112 76 103 ...
 $ Depth2       : logi  NA NA NA NA NA NA ...
 $ LL3          : int  NA NA 145 139 119 129 100 108 83 94 ...
 $ Depth3       : logi  NA NA NA NA NA NA ...
 $ LL4          : int  NA NA 152 128 135 124 107 93 90 90 ...
 $ Depth4       : logi  NA NA NA NA NA NA ...
 $ LL5          : int  NA NA 156 107 150 118 112 82 104 79 ...
 $ Depth5       : logi  NA NA NA NA NA NA ...
 $ LL6          : int  NA NA 159 102 153 111 107 76 115 72 ...
 $ Depth6       : logi  NA NA NA NA NA NA ...
 $ LL7          : int  NA NA 162 95 152 100 125 66 119 65 ...
 $ Depth7       : logi  NA NA NA NA NA NA ...
 $ LL8          : int  NA NA 163 92 154 86 129 56 123 58 ...
 $ Depth8       : logi  NA NA NA NA NA NA ...
 $ LL9          : logi  NA NA NA NA NA NA ...
 $ Depth9       : logi  NA NA NA NA NA NA ...
 $ LL10         : logi  NA NA NA NA NA NA ...
 $ Depth10      : logi  NA NA NA NA NA NA ...
 $ LL11         : logi  NA NA NA NA NA NA ...
 $ Depth11      : logi  NA NA NA NA NA NA ...
```
After dragging the LightLoc.csv file into GPE2 and exporting the results in .csv format I get somthing like this, which is rather different form the format seen in the  *Locations-GPE2.csv file available as an example: 
```
locs_GPE2 <- read.table("163273-LightLoc_porcessed.csv", sep = ',', header = T, blank.lines.skip = F)
str(locs_GPE2)
'data.frame':	102 obs. of  57 variables:
 $ Index        : int  NA NA 0 1 2 3 4 5 6 7 ...
 $ DeployID     : int  163273 163273 163273 163273 163273 163273 163273 163273 163273 163273 ...
 $ Ptt          : int  163273 163273 163273 163273 163273 163273 163273 163273 163273 163273 ...
 $ Instr        : Factor w/ 1 level "MINIPAT": 1 1 1 1 1 1 1 1 1 1 ...
 $ GeoDay       : Factor w/ 49 levels "","01-Jul-2017",..: 1 1 8 1 1 11 11 13 1 15 ...
 $ GeoTime      : Factor w/ 86 levels "","03:13:26",..: 1 1 64 1 1 33 52 38 1 17 ...
 $ GeoLong      : num  NA NA -52.2 NA NA ...
 $ GeoLongError : num  NA NA 0.234 NA NA ...
 $ GeoLat       : num  NA NA -41 NA NA -34.5 -38.5 -41 NA -39.5 ...
 $ GeoLatMSD    : num  NA NA 5.92 NA NA ...
 $ GeoLatU      : num  NA NA 35.5 NA NA ...
 $ GeoLatSError : num  NA NA 3.5 NA NA 2 1.5 4 NA 4.5 ...
 $ GeoLatNError : num  NA NA 2.5 NA NA 2 2 2.5 NA 3 ...
 $ Day          : Factor w/ 51 levels "01-Jul-2017",..: 6 39 8 8 10 10 12 12 14 14 ...
 $ Time         : Factor w/ 68 levels "00:00:00","09:07:30",..: 1 1 33 55 30 43 31 46 29 58 ...
 $ Time.Offset  : int  4 4 4 4 4 4 4 4 4 4 ...
 $ Count        : int  NA NA 9 9 11 11 8 8 10 10 ...
 $ InitLocQ     : int  NA NA NA NA NA NA NA NA NA NA ...
 $ InitLocTime  : Factor w/ 8 levels "","05-Jun-2017 00:00",..: 2 5 1 1 1 1 1 1 1 1 ...
 $ InitLat      : num  -35.5 -33.2 NA NA NA ...
 $ InitLong     : num  -52.5 -50 NA NA NA ...
 $ SSTTime      : Factor w/ 50 levels "","01-Jul-2017 07:00",..: 1 1 8 8 10 10 12 12 14 14 ...
 $ SSTDepth     : num  NA NA 9 9 6 6 6 6 17 17 ...
 $ SSTTemp      : num  NA NA 22.1 22.1 22.4 22.4 21.8 21.8 19.6 19.6 ...
 $ Type         : Factor w/ 4 levels "Begin","Dawn",..: 1 4 2 3 2 3 2 3 2 3 ...
 $ Delta        : int  NA NA 300 300 300 450 600 450 300 300 ...
 $ MinDepth     : int  NA NA 48 48 80 144 112 80 80 112 ...
 $ MaxDepth     : int  NA NA 80 208 240 336 272 208 240 272 ...
 $ AttenShallow : logi  NA NA NA NA NA NA ...
 $ AttenDeep    : logi  NA NA NA NA NA NA ...
 $ TravelMetric : logi  NA NA NA NA NA NA ...
 $ FoundPrevious: logi  NA NA NA NA NA NA ...
 $ K            : int  NA NA 19228 11361 42180 17090 18333 36329 10039 46974 ...
 $ LL0          : int  NA NA 119 156 97 145 67 124 65 119 ...
 $ Depth0       : logi  NA NA NA NA NA NA ...
 $ LL1          : int  NA NA 125 149 106 138 79 116 70 116 ...
 $ Depth1       : logi  NA NA NA NA NA NA ...
 $ LL2          : int  NA NA 133 142 113 134 96 112 76 103 ...
 $ Depth2       : logi  NA NA NA NA NA NA ...
 $ LL3          : int  NA NA 145 139 119 129 100 108 83 94 ...
 $ Depth3       : logi  NA NA NA NA NA NA ...
 $ LL4          : int  NA NA 152 128 135 124 107 93 90 90 ...
 $ Depth4       : logi  NA NA NA NA NA NA ...
 $ LL5          : int  NA NA 156 107 150 118 112 82 104 79 ...
 $ Depth5       : logi  NA NA NA NA NA NA ...
 $ LL6          : int  NA NA 159 102 -153 111 -107 76 115 72 ...
 $ Depth6       : logi  NA NA NA NA NA NA ...
 $ LL7          : int  NA NA 162 95 152 100 125 66 119 65 ...
 $ Depth7       : logi  NA NA NA NA NA NA ...
 $ LL8          : int  NA NA 163 92 154 86 129 56 123 58 ...
 $ Depth8       : logi  NA NA NA NA NA NA ...
 $ LL9          : logi  NA NA NA NA NA NA ...
 $ Depth9       : logi  NA NA NA NA NA NA ...
 $ LL10         : logi  NA NA NA NA NA NA ...
 $ Depth10      : logi  NA NA NA NA NA NA ...
 $ LL11         : logi  NA NA NA NA NA NA ...
 $ Depth11      : logi  NA NA NA NA NA NA ...
```
It seems that my issue is that I am not realizing how to make the exported results from the GPE2 have the same format and structure as the one in the "141259-Locations-GPE2.csv" example file. Am I missing somthing?

Thank you very much in advance Camrin!

**Comment by camrinbraun** [comment]
Indeed we rely on deprecated GPE2 (at least in this particular scenario) for light-based geolocation estimates. However, this should still work if you’re processing the light data via GPE2. You have to actually run the GPE2 algorithm which will yield light-based estimates of location. There’s a whole curve-fitting exercise to go through for that, although I can't seem to find the old manual for that. 

Option 1: I can give the curve-fitting a try for you with GPE2. Depends on how many tags you're trying to analyze.

Option 2: Estimate light-based positions (at least for longitude) using some other method of which there are several. @galuardi didn't you have some code for this relatively recently?

**Comment by fmasbervejillo** [comment]
Camrin, thanks for your reply.

I have indeed precessed the light data via GPE2 and got the light-based estimates of location, hence the new columns `$GeoDay`, `$GeoTime`, `$GeoLong`, `$GeoLongError`, `$GeoLat`, `$GeoLatMSD`, `$GeoLatU`, `$GeoLatSError`, `$GeoLatNError` on the 163273-LightLoc_porcessed.csv mentioned on my last entry.

However, this .csv file has a different format and structure than the one in the Package example (141259-Locations-GPE2.csv). I suspect that perhaps the GEP2 output needs some tweaking to be fited in the Locations.csv file, but if that was the case I am not sure how to populate the `$Error.radius`, `$Error.Semi.major.axis`, `$Error.Semi.minor.axis` and `$Error.Ellipse.orientation` fields, which are not products from the GPE2 algorithm run as far as I've been able to tell.

Am I missing something here?

I could send you via email one of the raw LightLoc.csv files if that helps.

Thanks again for your help!

**Comment by galuardi** [comment]
Hi guys, I'm weighing in very late! 

That's pretty odd that GPE2 is producing different column headers. However, the new header names actually make more sense. I would suggest two things

1. plot the lat/long data with error bars just to make sure things look sane
2. It's most likely that the `$GeoLatSError, $GeoLatNError` translate to $Error.Semi.major.axis and `$GeoLongError` is `$Error.Semi.minor.axis. `

We don't use (to my knowledge) the `$Error.Ellipse.orientation` in the HMMOCE process. 

I'm not sure what `$GeoLatMSD, $GeoLatU` represent but it would be worth finding out. MSD is probably mean squared distance... but distance from what? It may not matter as long as 2) works out. 

To @camrinbraun 's comment, I did have a process to get lat/long estimates simply using kftrack or ukfsst. This was for Microwave Telemetry tags. WC tags can be passed to trackit in a similar fashion . See here for more [Electronic Tagging Geolocation Packages Repository](https://github.com/positioning/kalmanfilter/wiki)

**Comment by fmasbervejillo** [comment]
Thanks, @camrinbraun and @galuardi.

I am gonna give it a try and see if it makes sense. Could the `$GeoLatU` be the `$Error.radius`?

**Comment by camrinbraun** [comment]
My interpretation of these GPE2 outputs is the same as @galuardi. Our formulation uses the "old" output vars to create an error ellipse around the most likely light-based location estimate. That ellipse is then used to formulate a likelihood that's later convolved with the other likeilhoods (e.g. sst-based likelihood). If you're having trouble getting things to line up, send us an example of your light data output from GPE2 and we'll take a shot at it.

**Comment by echinorhinus** [comment]
@fmasbervejillo , did you manage to figure this out?
I have had the same issue, and am looking for a work around.

**Comment by fmasbervejillo** [comment]
@echinorhinus , I am really sorry, It was my intention to reply to the thread but I got carried away doing other things and I totally forgot. To answer the question, yes, I was able to make it work with the suggestions made by @camrinbraun and @galuardi (huge thanks btw). My results actually make a lot of sense so I would dare to say that those suggestions actually solved my problem. 
I basically ended up populating the columns in the *-Locations-GPE2.csv file with the data from the GPE processed Lightloc.csv file. 
So I used the following data from the processed Lightloc.csv file to fill in the data in the Locations.csv file:
- `$GeoDay, $GeoTime` to populate `$date`
- `$GeoLong, $GeoLongError` to populate `$Longitude` and `$Error.Semi.minor.axis`, respectively
- `$GeoLat, $GeoLatSError` to populate `$Latitude` and `$Error.Semi.major.axis`, respectively. (Note: my tags were al deployed in the southern hemisphere and remained there so I didn't use the `$GeoLatNError`, but you should use this one with tags in the northern hemisphere. Not really sure what to do if your individual crosses the equator though, maybe a mix of both?)
- `$GeoLatMSD, $GeoLatU` to populate `$GPE.MSD` and `$GPE.U` (these are actually not used in the model so I don't really think it's necessary to migrate this data) 
- Then just complete the columns `$DeployID, $Ptt, $Instr` with your data

After that just make sure that your `$date` variable is correctly assigned to a propper <datetime> format when you load the .csv file into R. You should be able to calculate the likelihood raster (L1) with that and carry on with the modeling.

Let me know if I can be of any further help,

cheers

**Comment by camrinbraun** [comment]
It just occurred to me that perhaps @fmasbervejillo was using the wrong output file from WC-DAP. When I do the GPE2 processing:
* load all the data into DAP (usually just use File -> Import folder and point it to the whole folder of data as downloaded from the WC Portal)
* calculate the light-based locations as usual ending with "Save changes and close" in the light processing window. This takes you back to the DAP interface.
* then export to **popular formats**. One of the resulting files from that export is **-Locations** (I do **NOT** use -LightLoc output from GPE2/DAP). That file includes a column indicating the source of the location, which will typically be GPE-based position estimates (with associated error) as well as the Argos locations once the tag popped up. This output is what the example data in the package is based on.

So I wonder if @fmasbervejillo was looking for GPE outputs in the -Locations file from the WC Portal and/or not exporting the -Locations from DAP?

**Comment by echinorhinus** [comment]
@camrinbraun  @fmasbervejillo, that solved the problem! Thanks. I hadn't thought to re-process through DAP. Thank you :-)

**Comment by fmasbervejillo** [comment]
@camrinbraun @echinorhinus  I wasn't aware that you could perform the light processing within the DAP software. I tried it right now with one of my tags just to see if there were any differences with the MPTs estimated before. They seem to be in very close agreement, which I found a bit reassuring. However, doing it the way you pointed out above is much more straight forward as you don't need to migrate data from one file to another one.  
Thanks for the tip!

**Comment by camrinbraun** [comment]
Note this will change in future versions of `HMMoce` when we get smarter about light geolocation ;)
