### ISSUE TITLE
SST download error

### ISSUE THREAD

**Issue by camrinbraun** [camrinbraun/HMMoce#19]
From Federico Mas via email:

* While trying to get the env data for SST using the get.env function I keep getting the same error message: Error in curl_download(url, filename, quiet = FALSE) : HTTP error 404.
Normally this error is associated with a corrupted or no longer active link, cuold it be that this function is no longer working? I have no trouble downloading the depth-Temp HYCOM data using the same function though.

**Comment by camrinbraun** [comment]
I don’t have any issues downloading on my end. What is the URL the function prints out / generates before you get the error? For example, my function call and output looks like:

```
sst.udates <- as.Date('2018-01-01')
sp.lim <- list(lonmin = -165,
               lonmax = -150,
               latmin = 12,
               latmax = 25)
get.env(sst.udates, filename='mursst', type = 'sst', sst.type='mur', spatLim = sp.lim, save.dir = '~/Downloads/')
[1] "https://coastwatch.pfeg.noaa.gov/erddap/griddap/jplMURSST41.nc?analysed_sst[(2018-01-01T00:00:00Z):1:(2018-01-01T00:00:00Z)][(12):1:(25)][(-165):1:(-150)]"
 Downloaded 3782193 bytes...

```

I also suggest installing the dev version of the package from github (if you haven't already) like:

```
devtools::install_github('camrinbraun/HMMoce/', ref='dev')
```

**Comment by fmasbervejillo** [comment]
Thanks for your reply, Camrin.
Here's an example of my call and output:
```
wd<-paste(getwd())
sstFile <- paste(wd,"/163273-SST.csv",sep="")
tag.sst <- read.wc(ptt, sstFile, type = 'sst', tag=tag, pop=pop, verbose=T) 
sst.udates <- tag.sst$udates
tag.sst <- tag.sst$data

sp.lim <- list(lonmin = -60, lonmax = -40, latmin = -50, latmax = -25)

sst.dir <- paste(wd, '/sst-163273/', sep='')
dir.create(sst.dir, recursive = TRUE)
get.env(sst.udates, filename='BSH-oi', type = 'sst', sst.type='oi', spatLim = sp.lim, save.dir = sst.dir)
[1] "http://upwell.pfeg.noaa.gov/erddap/griddap/ncdcOisst2Agg_LonPM180.nc?sst[(2017-06-07T00:00:00Z):1:(2017-06-07T00:00:00Z)][(0):1:(0)][(-50):1:(-25)][(-60):1:(-40)]"
 [0%] Downloaded 0 bytes...
Error in curl_download(url, filename, quiet = FALSE) : HTTP error 404.
```
I have also tried to alternatively download the data changing the `sst.type` argument to 'ghr' but the same thing happens:
```
get.env(sst.udates, filename='BSH-163273-ghr', type = 'sst', sst.type='ghr', spatLim = sp.lim, save.dir = sst.dir)
[1] "http://upwell.pfeg.noaa.gov/erddap/griddap/jplG1SST.nc?SST[(2017-06-07T00:00:00Z):1:(2017-06-07T00:00:00Z)][(-50):1:(-25)][(-60):1:(-40)]"
 [0%] Downloaded 0 bytes...
Error in curl_download(url, filename, quiet = FALSE) : HTTP error 404.
```
 
I don't have this problem when I use the `get.env` function to download the HYCOM data:
```
get.env(pdt.udates, filename='BSH-hycom', type = 'hycom', spatLim = sp.lim, save.dir = hycom.dir)
[1] "http://ncss.hycom.org/thredds/ncss/GLBu0.08/expt_91.2?var=water_temp&north=-25.000000&west=-60.000000&east=-40.000000&south=-50.000000&horizStride=1&time_start=2017-06-06T00%3A00%3A00Z&time_end=2017-06-06T00%3A00%3A00Z&timeStride=1&addLatLon=true&disableProjSubset=on&vertCoord=&accept=netcdf"
 Downloaded 1759038 bytes...
```

Any thoughts?

**Comment by camrinbraun** [comment]
I can paste that URL that's returned when the function is first called into my browser window and get an immediate download so there's nothing wrong with the URL you're calling. Yet, when I call that same URL directly from R (eliminating anything happening inside the `HMMoce` function), I get the same error. For some reason, the upwell ERDDAP server isn't liking the download calls coming from within R regardless of method (e.g. `download.file`, `curl_download`). The same specs called to the coastwatch ERDDAP, however, works just fine. @fmasbervejillo are you comfortable implementing the call to the OISST dataset on [coastwatch](https://coastwatch.pfeg.noaa.gov/erddap/griddap/ncdcOisst2Agg_LonPM180.html) instead of upwell in the `get.oi.sst` function call? All the function does is build the URL in a piecewise fashion based on the inputs that are specified (e.g. date, spatial limits) using `sprintf`.

**Comment by fmasbervejillo** [comment]
Hi Camrin,

It seems to be working just fine now...
```
sst.dir <- paste(wd, '/sst-163273/', sep='')
dir.create(sst.dir, recursive = TRUE)
get.env(sst.udates, filename='BSH-163273-oi', type = 'sst', sst.type='oi', spatLim = sp.lim, save.dir = sst.dir)
[1] "https://upwell.pfeg.noaa.gov/erddap/griddap/ncdcOisst2Agg_LonPM180.nc?sst[(2017-06-07T00:00:00Z):1:(2017-06-07T00:00:00Z)][(0):1:(0)][(-50):1:(-25)][(-60):1:(-40)]"
 Downloaded 16091 bytes...[1] "https://upwell.pfeg.noaa.gov/erddap/griddap/ncdcOisst2Agg_LonPM180.nc?sst[(2017-06-08T00:00:00Z):1:(2017-06-08T00:00:00Z)][(0):1:(0)][(-50):1:(-25)][(-60):1:(-40)]"
```
Don't really know what happend as I have not changed anythig since my last attempt...

**Comment by camrinbraun** [comment]
The erddap servers can be quite finicky, and I don't have a good understanding of why that is. Glad its working and if you run into issues with upwell, I put a coastwatch version up as well https://github.com/camrinbraun/HMMoce/commit/e454b09119ea3d84ce9d95a022fb4c7fae425090. Eventually should have the base server as an optional input argument.
