### ISSUE TITLE
Issue with make.L

### ISSUE THREAD

**Issue by echinorhinus** [camrinbraun/HMMoce#20]
Hi @camrinbraun, I hit a bit of a bump in resampling and combining likelihoods (following the vignette with my own data), specifically at the call: L <- make.L(L1 = L.res[[1]][L.idx[[tt]]],
            L.mle.res = L.res$L.mle.res, dateVec = dateVec,
            locs.grid = locs.grid, iniloc = iniloc, bathy = bathy, pdt = pdt)

L1 = L.res[[1]][L.idx[[tt]]] produces a large list , while L.mle.res = L.res$L.mle.res produces a RasterBrick.
The two classes cannot be combined, (see the error message below) and I have been unable to figure how to convert either class to the same as it's partner.
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘resample’ for signature ‘"list", "RasterBrick"’

Any ideas on what the solution is?

**Comment by echinorhinus** [comment]
small update. I used traceback to find the point in the code where it's coming unstuck (see below)

![image](https://user-images.githubusercontent.com/8249991/80150810-e188f480-856d-11ea-802a-4edf5a8c7033.png)

Bathy and L are both classed as large lists, so I don't think the resample issue is occurring there.
Again, it seems to be because L1 is a list (of RasterBricks), while L.res.mle is a formal class RasterBrick.

**Comment by camrinbraun** [comment]
My interpretation is that resample is finding bathy of class "list" and L of class "RasterBrick". The latter is correct, thus this seems to be a product of your bathy object being of class "list" which `raster::resample` doesnt like. 

It looks like maybe you've fed a .nc file to `make.L()`? Or if you're trying to get your bathy (as raster) from a .nc use something like `bathy <- raster('my_bathy_nc_file.nc'). Either way, make sure your bathy input to `make.L` is of class raster.

**Comment by camrinbraun** [comment]
@echinorhinus did this solve the problem?
