### ISSUE TITLE
Issue with pulling OISST 

### ISSUE THREAD

**Issue by ehoff20** [camrinbraun/HMMoce#22]
Hi @camrinbraun, I hit a snag extracting SST data from the erddap website.  When I run the following code, I get the error below.

get.env(tdates, filename='oisst', type = 'sst', sst.type='oi', spatLim = sp.lim, save.dir = sst.dir)

[1] "https://upwell.pfeg.noaa.gov/erddap/griddap/ncdcOisst2Agg_LonPM180.nc?sst[(2018-11-21T00:00:00Z):1:(2018-11-21T00:00:00Z)][(0):1:(0)][(10):1:(32)][(-100):1:(-80)]"
 Downloaded 147 bytes...Error in curl_download(url, filename, quiet = FALSE) : HTTP error 400.
Called from: curl_download(url, filename, quiet = FALSE)

After contacting the erddap site, it sounds like they had made a change to the website. Now that while the product links have been corrected, there appears to be a change in the erddap call to the product.  It looks like the initial single layer z (surface depth) has been removed and the new erddap call is now...

https://upwell.pfeg.noaa.gov/erddap/griddap/ncdcOisst2Agg_LonPM180.nc?sst[(2018-11-21T00:00:00Z):1:(2018-11-21T00:00:00Z)][(10):1:(32)][(-100):1:(-80)]

**Comment by camrinbraun** [comment]
Sorry for the slow reply. This should be fixed with https://github.com/camrinbraun/HMMoce/commit/138d84e63410285d26ffb7f8e70af9314417b037. Give it a try and let me know?
