### ISSUE TITLE
Some doubts on Gatti_example.Rmd and hmm.diagnose

### ISSUE THREAD

**Issue by fmasbervejillo** [camrinbraun/HMMoce#24]
Hi @camrinbraun and @paulgatti,

I have gone through Paul's code (Gatti_example.Rmd) and made it to work quite well. However, I think I found a couple of possible errors/typos which I will detail below for your reference along with some questions that may help clarify the code for other users:

In Paul's code [https://github.com/camrinbraun/HMMoce/blob/dev/vignettes/Gatti_example.Rmd]:

- Line 320 goes like: `# pars sigma1 (resident), sigma2 (migrant), p11 switch from behavior 1 to 1 (remain resident), p22`
  After that, in line 321 you define these initial parameters [`pars.init=c(2,.2,.6,.8)`]. My guess is that the first parameter is, following the logic of the former method, the migration speed (not the resident speed), and the second parameter is the fraction of that speed that is attributed to the resident speed (hence the .2?). Is this correct? otherwise, the resident speed would be 10 fold the migratory speed.

- Line 346 to 270: when estimating the parameter via `nlminb()` an object `res.nlminb` is created, but when saving the .rda file the code calls the `res.optim` object instead of the `res.nlminb` one. I am guessing this is a mistake?

- I could make the new kernel estimations to work using the code, but I had to change it slightly as it calls a function `gausskern.pg()` which I couldn't find on git-hub. I swapped that one for `gausskern()` and it worked nicely. However, I am not entirely sure this is the right way to do it.

One last thing, but not really related to Paul's new code. I still have some trouble finding an objective way to decide which model (output results form different combinations of Light, SST, OH or HYCOM likelihoods for a given tag) is better. I've seen that there's a `hmm.diagnose()` function but it still seems to be under development. Any suggestions?

Thank you so much in advance!

cheers,

Federico

**Comment by camrinbraun** [comment]
Split into separate questions/issues
