### ISSUE TITLE
gausskern mod needed

### ISSUE THREAD

**Issue by camrinbraun** [camrinbraun/HMMoce#3]
We currently use calc.param() to figure out the dimensions of a gaussian movement kernel based on diffusive movement from a location at t-1. With slow diffusion speeds (approx < 0.5 m/s on a 1/4 deg grid), the kernel goes to a 1x1 matrix of probability 1, effectively keeping the movement constrained within the current grid cell during convolution with the likelihood surface.
Q1. Is this the desired behavior for, say, the residency state of a slow moving species like the blue shark? If so, how does this affect the model's ability to let diffusion occur and thus move into neighboring cells?

Q2. Resulting kernels with higher dimensions, say 4x4 or 9x9, result in rather "blocky" diffusion kernels. Is this appropriate?
![image](https://cloud.githubusercontent.com/assets/11963424/23554121/c5a1f4e2-fff1-11e6-92f9-f2e1db54ff35.png)

Q3. Should the above be normalized such that the highest probability of diffusion is 1 at the center of the kernel? Currently the distribution of values (~.25-.29 in this example) doesn't make sense when convolving with a likelihood surface of probability 0 to 1.

Q4. Is there a way to facilitate a smoother transition from the location at t-1 to the location at t with a diffusion kernel (e.g. needs to be less "blocky")? Is this purely an issue of grid cell size/resolution?
![image](https://cloud.githubusercontent.com/assets/11963424/23554219/297091e0-fff2-11e6-8f2b-c2f5532be672.png)

**Comment by camrinbraun** [comment]
@galuardi - doing this for our recordkeeping. there are several issues like this that we need to resolve. we can do so on here or use this as a record for the next time we get together.

**Comment by galuardi** [comment]
can you post a couple of lines of code that use calc.param()? 

currently, gausskern.r returns a kernel that sums to 1

`  kern = kern / (sum(sum(kern, na.rm = T), na.rm = T))
  kern[is.nan(kern)] = 0`

**Comment by camrinbraun** [comment]
we use it like this:
`par0 <- calc.param(migr.spd = 2, g = g)
D1 <- unlist(par0[1:2]) # parameters for kernel 1. this is migratory behavior mode
D2 <- unlist(par0[3:4]) # parameters for kernel 2. resident behavior mode
K1 <- gausskern(D1[1], D1[2], muadv = 0)
K2 <- gausskern(D2[1], D2[2], muadv = 0)
`

**Comment by galuardi** [comment]
1) I don't understand what's going in in calc.param function
last line
`return(list(migr = migr, sig1 = migr, resid = resid, sig2 = resid / 4))`

2) so, in the example, the migration mean and sd are identical, but the residential mean/sd are different. Also, in the example, the variable resid defaults to NULL, which means D2 (and K2) will be null

**Comment by camrinbraun** [comment]
1. `calc.param` is essentially a bit of a hack to get the dimensions right for generating the kernel. While it could be improved, I don't think that's our main issue here. The `return` is simply a list of the siz and sigma inputs to `gausskern`, one for migratory behavior and one for resident. `sig2 = resid/4` just adjusts the shape of the distribution from `gausskern` by forcing a smaller sigma (thus creating a higher likelihood at the center of the distribution and lower moving out, as opposed the more even distribution with a higher sigma as in the migratory case).

2. If resid isn't specified (and thus defaults to NULL) the function assumes it should be 10% of the migr speed. Again, a hack.

**Comment by galuardi** [comment]
`{r}
m1 = 2
r1 = m1/10

mu1 = (m1* 3600 * 24) /1000/111/dla^2
mu2 = (r1* 3600 * 24) /1000/111/dla^2

v1 = mu1
v2 = mu2/4

par(mfrow=c(2,2))

# K1 with two version of variance
image.plot(gausskern(mu1, v1))
image.plot(gausskern(mu1, v1/4))

# K2 with two version of variance
image.plot(gausskern(mu2, v2*4))
image.plot(gausskern(mu2, v2))

# suggested fix: keep the same mu term and make the kernel a function of the variance. This preserves the size of the kernel but should be effective in terms of probability density
image.plot(gausskern(mu1, v1)) # K1
image.plot(gausskern(mu1, v1/10)) # K2 
'

**Comment by camrinbraun** [comment]
What is `dla` in this example? 0.25?

**Comment by camrinbraun** [comment]
suggested fix
*keep the same mu term in both behavior states and just change the sigma for the different kernels. thus, dimensions are preserved but likelihood surface changes for different diffusion possibilities*
![image](https://cloud.githubusercontent.com/assets/11963424/23556680/6e872934-fffb-11e6-8a55-8bcdae5744e9.png)

**Comment by galuardi** [comment]
exactly. maybe it works?!

**Comment by camrinbraun** [comment]
using 2 m/s for a blue shark:
![image](https://cloud.githubusercontent.com/assets/11963424/23556943/443f9a3e-fffc-11e6-84e7-8e2a814693ab.png)

This reiterates Q2: is the "blockiness" of this kernel appropriate? It seems necessary that the dimensions of the movement kernel be represented in this way so the convolution works properly. The "blockiness" comes from the relatively low resolution at which we're operating (1/4 deg) combined with the slow speeds of blue shark movement (2 m/s).
