### ISSUE TITLE
Lotek incompatibility within calc.lightloc

### ISSUE THREAD

**Issue by marosteg** [camrinbraun/HMMoce#35]
Within calc.lightloc(), there is a call seemingly unique to WC tags that already provide the light-location error estimates - this results in the following error when attempting to run the function off an etuff-formatted Lotek tag. For example (from run_albacore.R):
```
calc.lightloc(tr, locs.grid = locs.grid, dateVec = dateVec,
                         errEll = FALSE)
```
Yields...
```
Error in if (light.t$Error.Semi.minor.axis[1] < 1e+05) light.t$Error.Semi.minor.axis[1] <- 1e+05 : 
  argument is of length zero
```
This occurs because the function assumes the Lotek input already has a column of name "Error.Semi.minor.axis", which it does not.

**Comment by camrinbraun** [comment]
solved and merged to `-dev` with #36
