### ISSUE TITLE
Incorporating known location in make.L

### ISSUE THREAD

**Issue by marosteg** [camrinbraun/HMMoce#40]
I am running into an error I can't seem to crack with respect to incorporating known locations into the list of final likelihoods. I run:
`
L <- make.L(L.res$L.rasters, iniloc = iniloc, dateVec = dateVec, known.locs = kl)
`
where object _kl_ is a df with columns "date", "lat", and "lon". I get this error:
`
Error in .doCellFromXY(object@ncols, object@nrows, object@extent@xmin,  : 
  Not compatible with requested type: [type=list; target=double].
`
which is occurring where the known location is supposed to be assigned a likelihood of 1 on the given day.

Also, having looked into incorporation of known locations into make.L, I think that this is something that should be revisited for improvement - as it just picks the first location on a day as the "known" informing the likelihood, rather than (if using Argos) the highest quality location class and lowest error estimate therein.

**Comment by galuardi** [comment]
this almost certainly has to do with the object types in the `kl` object. Maybe the dates or geometry? Hard to tell. 

On the second point, I would suggest that the `kl` object be constructed a priori with the best location per/day (or row). That part doesn't need to be hard coded in `make.L` necessarily.

**Comment by marosteg** [comment]
Turns out that my `kl` was somehow generated as a tibble, which was causing the problem. It registered TRUE for both is.data.frame() and is_tibble(), but then using as.data.frame() then maintained is.data.frame() as TRUE but changed is_tibble() to FALSE.

However, upon checking the output, while I am seeing the grid cell of the known location marked as likelihood = 1, the rest of the raster layer has not been changed to likelihood = 0. In the fig below, the known location cell is marked by the purple arrow.
![fullsizeoutput_34c9](https://user-images.githubusercontent.com/56367866/110009200-b2452700-7cea-11eb-8f2b-a9c9dba0ca53.jpeg)
