### ISSUE TITLE
proper function of convolution?

### ISSUE THREAD

**Issue by camrinbraun** [camrinbraun/HMMoce#5]
## the problem:
the output of a given convolution of a likelihood layer (f$phi) with the migratory movement kernel (K1) has a very flat distribution of likelihood values (q1). this process occurs at the beginning of the `for` loop in hmm.filter.

previous day's f$phi:
![image](https://cloud.githubusercontent.com/assets/11963424/23557812/540dcb7c-ffff-11e6-94c8-95e7598655c2.png)

movement kernel:
![image](https://cloud.githubusercontent.com/assets/11963424/23557817/5bf08b36-ffff-11e6-94ab-18b768757dad.png)

resulting output w/ very flat distribution of likelihood values:
![image](https://cloud.githubusercontent.com/assets/11963424/23557832/6ee8a39a-ffff-11e6-8fd4-a8545de6880f.png)

## the question:
is this how the convolution is supposed to function? it seems like the output should have a more even falloff in the distribution, similar to the kernel.

**Comment by camrinbraun** [comment]
@galuardi - is this a result of the flat distribution of the movement kernel (range .86 to 1)? I don't think the output from the convolution should be so binary, right?

**Comment by galuardi** [comment]
i thought the movement kernel was not normalized?

**Comment by camrinbraun** [comment]
this issue is the same whether the kernel is normalized or not. it seems that the kernel does need to be normalized so I've implemented that, but it doesn't affect this issue.

**Comment by camrinbraun** [comment]
```{r}
K1 <- gausskern(6, 6)
K2 <- gausskern(6, 0.6)
K1r <- plotrix::rescale(K1, c(0.1,1))
K2r <- plotrix::rescale(K2, c(0.1,1))  
```

![image](https://cloud.githubusercontent.com/assets/11963424/23872806/0e9614d2-0806-11e7-8ef6-eb625f5b8c0f.png)

**Comment by camrinbraun** [comment]
Turns out this has negligible effect on the results so we'll leave ```{r}gausskern``` as is.
