### ISSUE TITLE
get.bath.data: raster param removed, pull reference from @return

### ISSUE THREAD

**Issue by SimonDedman** [camrinbraun/HMMoce#53]
Cam, hello mate hope you're well. Tiny one - using the dev version of `HMMoce`, `get.bath.data`, `raster` is still referenced as a param in the docs but is no longer an actual function parameter.

Also oddly when I install via:

```
devtools::install_github('camrinbraun/HMMoce', ref = 'dev')
library(HMMoce)
```
The man page still lists the old parameters, `lonlow` etc. Not sure why.

And finally:

`spatLim` info,

`\code{list(xmin, xmax, ymin, ymax)}`

should be

`\code{list(lonmin, lonmax, latmin, latmax)}`

Cheers!

Simon

**Comment by camrinbraun** [comment]
fixed with #54 updated the `.R` file and associated man (doc) page.

thanks @SimonDedman !!
