### ISSUE TITLE
Longitude Range Spanning 0 when Downloading HYCOM (raster cutoff)

### ISSUE THREAD

**Issue by marosteg** [camrinbraun/HMMoce#55]
I am currently downloading SST, HYCOM, and bathymetry data from the longitude range -10 to 42 (i.e., spanning 0). The resulting SST and bathymetry rasters correctly show data from -10 to 42, whereas the HYCOM raster cuts off the raster west of 0 and only presents data in the range 0 to 42. 

@camrinbraun solved this issue when spanning the 180/-180 transition for the Pacific albacore application but this will need to be addressed for any project occurring in the Norwegian, North, or western Med Sea, as well as eastern South Atlantic (none of which have previously been the study area for an HMMoce study, to my knowledge).

**Comment by camrinbraun** [comment]
So the issue then is HYCOM is missing the data from -10 E to 0 in longitude? If yes, can you please provide a couple lines of simple code that allow me to recreate the same spatial and temporal extent of your HYCOM request? That will help me quickly re-create the issue so I can isolate it.

**Comment by marosteg** [comment]
Yes, missing data from -10 to 0. This code should work:
```
dir <- 'enter your directory here'

tag <- as.POSIXct(paste(15, "/", 8, "/", 2020,
                        sep = ""), format = "%d/%m/%Y", tz = "UTC")
pop <- as.POSIXct(paste(16, "/", 8, "/", 2020,
                        sep = ""), format = "%d/%m/%Y", tz = "UTC")

udates <- seq.Date(as.Date(tag), as.Date(pop), by = "day")
sp.lim <- list(lonmin = -10, lonmax = 42, latmin = 30, latmax = 46)

hycom.dir <- paste0(dir, "EnvData/hycom/")
if (!dir.exists(hycom.dir)) dir.create(hycom.dir, recursive = TRUE)

for (i in 1:length(udates)){
  if (!file.exists(paste0(hycom.dir, "hycom_", udates[i], ".nc"))) get.env(udates[i],
                                                                           filename = "hycom", type = "hycom", spatLim = sp.lim, save.dir = hycom.dir)
}

b <- raster::brick(paste0(hycom.dir, "hycom_", udates[1], ".nc"))
raster::plot(b[[1]],main="Temp at 0 m")
fields::world(add = T)

#note how raster currently stops at longitude 0 (east of Gibraltar), 
#whereas it should stop at -10 longitude (west of Gibraltar)
```

**Comment by camrinbraun** [comment]
give this another shot with https://github.com/camrinbraun/HMMoce/tree/hycom360

seems to be working for me after these changes:
<img width="657" alt="Screen Shot 2021-09-17 at 7 39 46 AM" src="https://user-images.githubusercontent.com/11963424/133776713-50cfa473-c1ec-4024-a18d-644003b5bf79.png">

**Comment by marosteg** [comment]
Looks good in testing!
