### ISSUE TITLE
Separate Lat and Lon Likelihood Surfaces

### ISSUE THREAD

**Issue by marosteg** [camrinbraun/HMMoce#63]
It would be beneficial to enable calculation of separate latitude and longitude likelihoods given the frequently greater error in the former. For example, when filtering Microwave Telemetry light-based positions, more latitudes than longitudes may be removed. Separate likelihoods here would allow longitude to inform more days than if it had to be combined with latitude (which is limited to the number of good latitude estimates).

**Comment by camrinbraun** [comment]
started the simplest implementation of the lat-only option with #64 

i'm all for other light-based approaches mentioned above if someone wants to take a crack. for now, the lat-only approach should work wtih

`calc.lightloc(..., errEll = FALSE, lon_only = FALSE)` 

where the latter argument is new. @marosteg can you test this and let me know if it works as expected?

**Comment by marosteg** [comment]
This currently yields an error:
```
L.light <- calc.lightloc(lightloc, locs.grid = locs.grid, dateVec = dateVec,
                         errEll = FALSE, lon_only=FALSE)
Error in calc.lightloc(lightloc, locs.grid = locs.grid, dateVec = dateVec,  : 
  unused argument (lon_only = FALSE)
```
This is because the param lon_only is not defined in line #46 of calc.lightloc.r

**Comment by camrinbraun** [comment]
and now with my latest push?

**Comment by marosteg** [comment]
Works beautifully! Awesome addition to HMMoce for MTI tags.

**Comment by camrinbraun** [comment]
@galuardi or @marosteg planning to make more sophisticated changes to how we treat light in the near future or are we content with this solution for now?

**Comment by marosteg** [comment]
I'm good with this solution for now.
