### ISSUE TITLE
GPE2 location output not compatible with  calc.lightloc.r

### ISSUE THREAD

**Issue by galuardi** [camrinbraun/HMMoce#65]
Jeff Kneebone provided a file generated from **GPE2 v.2.00.0027**

The lat error is now separated into N and S components. All errors are in degrees. This may be straightforward to use with either some data wrangling or changes to the  `calc.lightloc.r` function. 

The real question is treatment of the Lat error in this format. In the examples, semi.major.axis is symmetrical. thoughts? 

[LightLoc-GPE2_example.csv](https://github.com/camrinbraun/HMMoce/files/7944657/LightLoc-GPE2_example.csv)

**Comment by camrinbraun** [comment]
@galuardi what did you come up with as a solution? be good to document that here or otherwise keep track of the needed improvements

**Comment by galuardi** [comment]
@camrinbraun , Jeff used the protocol in issue 18 to generate a data frame
