### ISSUE TITLE
calc.ohc/calc.hycom and the .par versions

### ISSUE THREAD

**Issue by marosteg** [camrinbraun/HMMoce#79]
In all four of these functions, the application of an IF statement to _class(lik.try)_ or the object _class.try_ yields a 'condition has length > 1' error when the class is not the singular "try-error" and is instead the length-two vector of "matrix" "array". I believe rewriting with the any() function included in the IF statement will prevent the 'condition has length > 1' error. The issue is restricted to the following sections of code:

calc.ohc:               lines 203-228
calc.ohc.par:        lines 211-231
calc.hycom:          lines 167-207
calc.hycom.par:   lines 179-281

This is running off of the most recent version of 'dev' branch and the issue precedes (and persisted through) the recent merges.

**Comment by camrinbraun** [comment]
hopefully fixed on `dev` with [9610eae](https://github.com/camrinbraun/HMMoce/commit/9610eae22e849e768354bb684bd244639c17ecda)
