### ISSUE TITLE
read.wc when PDT is surface-only

### ISSUE THREAD

**Issue by marosteg** [camrinbraun/HMMoce#81]
read.wc ends the pdt data frame short (with respect to deployment days) when the -PDTs.csv file has a surface-only entry. Error can be tested with spearfish 227133 at:

MPG_WHOI/data/shortbill_spearfish/MiniPAT/227133

**Comment by camrinbraun** [comment]
should be all set with [debf6bc](https://github.com/camrinbraun/HMMoce/commit/debf6bc8443bbf5dbde8b79c0a8fd06ef949b1a7)
